### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered 

### ISSUE THREAD

**Issue by wrmichaelmak** [cfzd/Ultra-Fast-Lane-Detection#242] opened 2021-07-29 09:32 UTC
I faced this error when trying to fine-tune the model from `tusimple_18` weights. I set `num_lanes` to 2 and I am training on a custom dataset. Previously, I had successfully trained the model on my custom dataset but I set the `num_lanes` to 4. I wondered if that's the problem

<img width="920" alt="Screenshot 2021-07-29 at 10 28 46" src="https://user-images.githubusercontent.com/40602206/127468479-1260faa4-ee76-4114-8e22-7ce7619658a2.png">

**Comment by cfzd** [comment] 2021-07-30 12:49
@wrmichaelmak 
It might be caused by the segmentation branch, could you please try to disable the segmentation branch?

**Comment by wrmichaelmak** [comment] 2021-07-30 14:20
@cfzd 
Yes, you are right I disabled the auxiliary segmentation branch and it starts working. I am just wondering, if i disabled the segmentation branch, will the iou be not calculated?

**Comment by cfzd** [comment] 2021-07-31 03:02
@wrmichaelmak 
Of course, iou will be invalid since no segmentation is involved.

**Closed** 2021-08-03 23:19 UTC
